workflow:
  rules:
    # For merge requests
    - if: "$CI_MERGE_REQUEST_IID"
    # For commit into master
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
    # For commit into dev branch
    - if: '$CI_COMMIT_BRANCH == "dev"'
    # For tags
    - if: "$CI_COMMIT_TAG"

variables:
  # Where to store pip cache
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip-cache"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .cache/pip-cache

stages:
  - ci setup
  - code quality
  - test

image: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA

Build and Push CI Docker Image:
  stage: ci setup
  image: docker:20.10.8
  interruptible: true
  services:
    - name: docker:20.10.8-dind
      command: ["--insecure-registry", "registry.bigdata"]
  variables:
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - echo -n $CI_REGISTRY_TOKEN | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
  script:
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build -f Dockerfile.ci --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA --tag $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
    - docker push $CI_REGISTRY_IMAGE:latest

syntax-checker:
  stage: code quality
  rules:
    - if: '$CI_MERGE_REQUEST_IID'
      allow_failure: false
    - allow_failure: true
  interruptible: true
  before_script:
    - python -V
    - pip install flake8 isort
    # Print changed files (except deleted)
    - git diff --diff-filter=d --name-only origin/$CI_MERGE_REQUEST_TARGET_BRANCH_NAME
  script:
    - PYTHON_TOUCHED_FILES=$(git diff --diff-filter=d --name-only origin/$CI_MERGE_REQUEST_TARGET_BRANCH_NAME | { grep -E '\.py$' || :; })
    - |
      if [[ -n "$CI_MERGE_REQUEST_IID" ]]; then
        if [[ -n "$PYTHON_TOUCHED_FILES" ]]; then
          flake8 $PYTHON_TOUCHED_FILES --exclude=docs,htmlcov,venv,.cache,.coverage,.git
          isort -c $PYTHON_TOUCHED_FILES
        fi
      else
        flake8 --exclude=docs,htmlcov,venv,.cache,.coverage,.git
        isort -c *
      fi

docstring-checker:
  stage: code quality
  allow_failure: true
  interruptible: true
  before_script:
    - python -V
    - pip install docstr-coverage
    # Print changed .py files (except deleted)
    - git diff --diff-filter=d --name-only origin/$CI_MERGE_REQUEST_TARGET_BRANCH_NAME | { grep -E '\.py$' || :; }
  script:
    - PYTHON_TOUCHED_FILES=$(git diff --diff-filter=d --name-only origin/$CI_MERGE_REQUEST_TARGET_BRANCH_NAME | { grep -E '\.py$' || :; })
    - |
      if [[ -n "$CI_MERGE_REQUEST_IID" ]]; then
        if [[ -n "$PYTHON_TOUCHED_FILES" ]]; then
          docstr-coverage $PYTHON_TOUCHED_FILES --config .docstr.yml
        fi
      else
        docstr-coverage * --badge=badge.svg --config .docstr.yml
      fi
  artifacts:
    paths:
      - badge.svg

unit-test:
  stage: test
  interruptible: true
  before_script:
    - python -V
    - ls -al
    - apt update && apt install -y git
    - pip install .[dev]
  script:
    - pytest --cov=. -vvv --disable-warnings
