FROM python:3.8-slim


COPY package.list /
RUN apt-get update \
    && apt-get install -y --no-install-recommends $(cat /package.list)\
    && apt-get autoremove -yqq --purge \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt /
COPY requirements-dev.txt /

RUN pip install --no-cache-dir -r /requirements.txt && \
    pip install --no-cache-dir Cython && \
    pip install --no-cache-dir -r /requirements-dev.txt || true
