FROM python:3.8-slim


COPY requirements*.txt /

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        git \
        build-essential \
    && apt-get autoremove -yqq --purge \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir \
    -r /requirements.txt \
    -r /requirements-dev.txt
