from typing import Optional

import pandas as pd
from jinja2 import BaseLoader
from jinja2.nativetypes import NativeEnvironment

from ..fs import FileSystem
from ..history_template import get_series


class BaseStatement:
    """Base abstract statement class for all Deirokay statements.

    Parameters
    ----------
    options : dict
        Statement parameters provided by user.
    read_from : Optional[FileSystem], optional
        Where read past validation logs from
        (necessary for templated moving statistics).
        By default None.

    Attributes
    ----------
    name : str
        Statement name when referred in Validation Documents (only
        valid for non-custom statements).
    expected_parameters : List[str]
        Parameters expected for this statement.
    table_only : bool
        Whether or not this statement in applicable only to the entire
        table, instead of scoped columns.
    jinjaenv : NativeEnvironment
        Jinja Environment to use when rendering templates. Only for
        advanced users.
    """

    name = 'base_statement'
    expected_parameters = ['type', 'severity', 'location']
    table_only = False
    jinjaenv = NativeEnvironment(loader=BaseLoader())

    def __init__(self, options: dict, read_from: Optional[FileSystem] = None):
        self._validate_options(options)
        self.options = options
        self._read_from = read_from
        self._parse_options()

    def _validate_options(self, options: dict):
        """Make sure all providded statement parameters are expected
        by statement classes"""
        cls = type(self)
        unexpected_parameters = [
            option for option in options
            if option not in (cls.expected_parameters +
                              BaseStatement.expected_parameters)
        ]
        if unexpected_parameters:
            raise ValueError(
                f'Invalid parameters passed to {cls.__name__} statement: '
                f'{unexpected_parameters}\n'
                f'The valid parameters are: {cls.expected_parameters}'
            )

    def _parse_options(self):
        """Render Jinja templates in statement parameters."""
        for key, value in self.options.items():
            if isinstance(value, str):
                rendered = (
                    BaseStatement.jinjaenv.from_string(value)
                    .render(
                        series=lambda x, y: get_series(x, y, self._read_from)
                    )
                )
                self.options[key] = rendered

    def __call__(self, df: pd.DataFrame):
        """Run statement instance."""
        internal_report = self.report(df)
        result = self.result(internal_report)

        final_report = {
            'detail': internal_report,
            'result': result
        }
        return final_report

    def report(self, df: pd.DataFrame) -> dict:
        """Receive a DataFrame containing only columns on the scope of
        validation and returns a report of related metrics that can
        be used later to declare this Statement as fulfilled or
        failed.

        Parameters
        ----------
        df : pd.DataFrame
            The scoped DataFrame columns to be analysed in this report
            by this statement.

        Returns
        -------
        dict
            A dictionary of useful statistics about the target columns.
        """
        return {}

    def result(self, report: dict) -> bool:
        """Receive the report previously generated and declare this
        statement as either fulfilled (True) or failed (False).

        Parameters
        ----------
        report : dict
            Report generated by `report` method. Should ideally
            contain all statistics necessary to evaluate the statement
            validity.

        Returns
        -------
        bool
            Whether or not this statement passed.
        """
        return True

    @staticmethod
    def profile(df: pd.DataFrame) -> dict:
        """Given a template data table, generate a statement dict
        from it.

        Parameters
        ----------
        df : pd.DataFrame
            The DataFrame to be used as template.

        Returns
        -------
        dict
            Statement dict.
        """
        raise NotImplementedError
